name: 'slack-notify'
description: 슬랙으로 알림 전송

# input으로 받을 값들
inputs:
  status:
    description: status는 빌드 상태를 의미(success 또는 failure). 값이 들어오지 않는다면 기본 값으로 failure를 사용
    required: false
    default: 'failure'
  slack_webhook_url:
    description: 슬랙 웹훅 URL
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send slack message
      shell: bash
      run: |
         if [ "${{ inputs.status }}" = "success" ]; then
           EMOTICON="✅"
         else
           EMOTICON="⛔️"
         fi

         MSG="{ \"text\":\">${EMOTICON} workflow (<https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|${GITHUB_WORKFLOW}>) in <https://github.com/${GITHUB_REPOSITORY}|${GITHUB_REPOSITORY}>\n><https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks|${GITHUB_JOB}> job ${{ inputs.status }}, branch=\`${GITHUB_REF#refs/heads/}\`\"}"
        
         # Slack에 보낼 메시지 내용
         curl -X POST -H 'Content-type: application/json' --data "${MSG}" "${{ inputs.slack_webhook_url }}"
