name: Continuous Integration (prod)

on:
  pull_request:
    branches: [ "release" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

permissions:
  contents: read

jobs:
  production-test:
    runs-on: ubuntu-22.04
    env:
      REPO: ${{ secrets.DOCKER_REPOSITORY }}

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up App configuration
        run: |
          echo "${{ secrets.APPLICATION_TEST }}" > ./src/test/resources/application-test.yml
        shell: bash

      - name: Test App
        run: ./gradlew clean test


      - name: Send slack when failed
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          status: failure
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_BACKEND_TEAM_URL }}

      - name: Send slack if completed
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        with:
          status: success
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_BACKEND_TEAM_URL }}
